version: '3'

services:
  social-network-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  social-network-app:
    image: social-network
    restart: on-failure
    depends_on:
      - social-network-db
    ports:
      - 8090:8090
