# Security config
security:
  token_expiration_time: 3600000
  signing_key: some-signing-key

spring:
  datasource:
    password: root
    url: jdbc:mysql://social-network-db:3306/social-network?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    default-property-inclusion: non_null

# Server properties
server:
  port: 8090
