# Security config
security:
  token_expiration_time: 1800000
  signing_key: some-signing-key

# DB config
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/KpiSocialNetwork
    username: root
  jpa:
    hibernate:
      ddl-auto: update
